name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - type: bind
        source: ./server/config.ini
        target: /config.ini
    networks:
      - testing_net

  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=1
    volumes:
      - type: bind
        source: ./client/config.yaml
        target: /config.yaml
      - ./.data/dataset/agency-1.csv:/agency.csv
    networks:
      - testing_net
    depends_on:
      - server
  client2:
    container_name: client2
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=2
    volumes:
      - type: bind
        source: ./client/config.yaml
        target: /config.yaml
      - ./.data/dataset/agency-2.csv:/agency.csv
    networks:
      - testing_net
    depends_on:
      - server
  client3:
    container_name: client3
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=3
    volumes:
      - type: bind
        source: ./client/config.yaml
        target: /config.yaml
      - ./.data/dataset/agency-3.csv:/agency.csv
    networks:
      - testing_net
    depends_on:
      - server
  client4:
    container_name: client4
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=4
    volumes:
      - type: bind
        source: ./client/config.yaml
        target: /config.yaml
      - ./.data/dataset/agency-4.csv:/agency.csv
    networks:
      - testing_net
    depends_on:
      - server
  client5:
    container_name: client5
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=5
    volumes:
      - type: bind
        source: ./client/config.yaml
        target: /config.yaml
      - ./.data/dataset/agency-5.csv:/agency.csv
    networks:
      - testing_net
    depends_on:
      - server

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
    